name: CICD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
    compile:
       runs-on: self-hosted
       
       steps:
       - uses: actions/checkout@v7
       - name: set up JDK17
         uses: actions/setup-java@v5
         with:
           java-version: "17"
           distribution: 'temurin'
           cache: maven

       - name: build with maven
         run: mvn compile

    security-checks:
      runs-on: self-hosted
      needs: compile

      steps:
      - uses: actions/checkout@v7

      
      # Step 2: Run Trivy with the --offline flag so it uses the cache  
      - name: trivy innstallation
        run: |
           sudo apt-get install -y wget gnupg
           wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
           echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
           sudo apt-get update -y
           sudo apt-get install -y trivy
          
      - name: trivy FS Scan
        run: trivy fs --format table -o fs-report.json .

      - name: gitleaks installation
        run: sudo apt install gitleaks -y
      - name: gitleaks Code Scan
        run: gitleaks detect source . -r gitleaks-report.json -f json

    test:
      runs-on: self-hosted
      needs: security-checks

      steps:
        - uses: actions/checkout@v7
        - name: setup JDK 17
          uses: actions/setup-java@v5
          with:
              java-version: "17"
              distribution: 'temurin'
              cache: maven
        - name: Runn Unit test
          run: mvn test

    build_project_and_sonar_scan:
      runs-on: self-hosted
      needs: test
       
      steps:
        - uses: actions/checkout@v7
        - name: setup JDK 17
          uses: actions/setup-java@v5
          with:
              java-version: "17"
              distribution: 'temurin'
              cache: maven
        - name: build project
          run: mvn package

        - uses: actions/checkout@v5
          with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
           fetch-depth: 0
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v8.2.1 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

        - name: SonarQube Quality Gate check
          id: sonarqube-quality-gate-check
          uses: sonarsource/sonarqube-quality-gate-action@master
          with:
            pollingTimeoutSec: 600
          env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} #OPTIONAL
      
          
      
    
          
        
   
    
    
 
