name: aws infr provisionng pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'eks-terraform/**' #  IGNORES triggers if you only modify your infrastructure code

jobs:
  provision-infra:
    runs-on: self-hosted 
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 


    - name: Terraform Init
      run: terraform -chdir=eks-terraform init

    - name: Terraform Apply
      run: terraform -chdir=eks-terraform apply -auto-approve
